### ISSUE TITLE
Cloning

### ISSUE THREAD

**Issue by UnEnanoMas** [PocketMineItalianDevs/TapToArmor#2]
When you click to put on the armor, it stays also in the inventory, is what happens in the majority of servers with that plugin

**Comment by RubyTemple** [comment]
@UnEnanoMas Che

**Comment by RubyTemple** [comment]
@UnEnanoMas Can you send a video please?

**Comment by UnEnanoMas** [comment]
https://file.io/btHuJEVg

:)

32.5MB

**Comment by RubyTemple** [comment]
@UnEnanoMas File not found.

**Comment by UnEnanoMas** [comment]
https://gofile.io/d/jwPo7q

**Comment by RubyTemple** [comment]
@UnEnanoMas What plugins do you have on the server?

**Comment by UnEnanoMas** [comment]
87 (I don't like to share which plugins I use losiento, but can it be by TeaSpoon?) idk

**Comment by RubyTemple** [comment]
@UnEnanoMas Try without any other plugins

**Comment by UnEnanoMas** [comment]
I have only opened this problem to see if you can help other people who have the same problem, I do not use this plugin since another does the same so it does not help me to have 2 equal

Equally good job
